/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebWorkerRouteImport } from './routes/web-worker'
import { Route as StreamingRouteImport } from './routes/streaming'
import { Route as FreezingRouteImport } from './routes/freezing'
import { Route as IndexRouteImport } from './routes/index'

const WebWorkerRoute = WebWorkerRouteImport.update({
  id: '/web-worker',
  path: '/web-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingRoute = StreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const FreezingRoute = FreezingRouteImport.update({
  id: '/freezing',
  path: '/freezing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/freezing': typeof FreezingRoute
  '/streaming': typeof StreamingRoute
  '/web-worker': typeof WebWorkerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/freezing': typeof FreezingRoute
  '/streaming': typeof StreamingRoute
  '/web-worker': typeof WebWorkerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/freezing': typeof FreezingRoute
  '/streaming': typeof StreamingRoute
  '/web-worker': typeof WebWorkerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/freezing' | '/streaming' | '/web-worker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/freezing' | '/streaming' | '/web-worker'
  id: '__root__' | '/' | '/freezing' | '/streaming' | '/web-worker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreezingRoute: typeof FreezingRoute
  StreamingRoute: typeof StreamingRoute
  WebWorkerRoute: typeof WebWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-worker': {
      id: '/web-worker'
      path: '/web-worker'
      fullPath: '/web-worker'
      preLoaderRoute: typeof WebWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming': {
      id: '/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof StreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freezing': {
      id: '/freezing'
      path: '/freezing'
      fullPath: '/freezing'
      preLoaderRoute: typeof FreezingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreezingRoute: FreezingRoute,
  StreamingRoute: StreamingRoute,
  WebWorkerRoute: WebWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
