/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebWorkerRouteImport } from './routes/web-worker'
import { Route as MainThreadRouteImport } from './routes/main-thread'
import { Route as IndexRouteImport } from './routes/index'

const WebWorkerRoute = WebWorkerRouteImport.update({
  id: '/web-worker',
  path: '/web-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const MainThreadRoute = MainThreadRouteImport.update({
  id: '/main-thread',
  path: '/main-thread',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main-thread': typeof MainThreadRoute
  '/web-worker': typeof WebWorkerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main-thread': typeof MainThreadRoute
  '/web-worker': typeof WebWorkerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/main-thread': typeof MainThreadRoute
  '/web-worker': typeof WebWorkerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/main-thread' | '/web-worker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/main-thread' | '/web-worker'
  id: '__root__' | '/' | '/main-thread' | '/web-worker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainThreadRoute: typeof MainThreadRoute
  WebWorkerRoute: typeof WebWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-worker': {
      id: '/web-worker'
      path: '/web-worker'
      fullPath: '/web-worker'
      preLoaderRoute: typeof WebWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main-thread': {
      id: '/main-thread'
      path: '/main-thread'
      fullPath: '/main-thread'
      preLoaderRoute: typeof MainThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainThreadRoute: MainThreadRoute,
  WebWorkerRoute: WebWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
